# Generated by Django 5.2.8 on 2025-11-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_folder_id', models.CharField(max_length=255)),
                ('year_folder_id', models.CharField(max_length=255)),
                ('month_folder_id', models.CharField(max_length=255)),
                ('date_folder_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'email_folder_id', 'year_folder_id', 'month_folder_id', 'date_folder_id')},
            },
        ),
    ]
