# Generated by Django 5.0.7 on 2025-11-06 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationApp', '0002_emailfolder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailfolder',
            options={'ordering': ['-folder_date']},
        ),
        migrations.AlterUniqueTogether(
            name='emailfolder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='folder_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='folder_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='folder_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterUniqueTogether(
            name='emailfolder',
            unique_together={('email', 'folder_year', 'folder_month', 'folder_date')},
        ),
    ]
