# Generated by Django 5.2.8 on 2025-11-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationApp', '0003_alter_emailfolder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfolder',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
