# Generated by Django 5.2.8 on 2025-11-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationApp', '0004_emailfolder_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailfolder',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='emailfolder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_trucks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
