# Generated by Django 5.2.8 on 2025-11-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automationApp', '0007_logentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailfolder',
            old_name='email_folder_id',
            new_name='company_name_folder_id',
        ),
    ]
