# Generated by Django 5.2.8 on 2025-11-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationApp', '0008_rename_email_folder_id_emailfolder_company_name_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfolder',
            name='company_name_mc_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
